Test
MartynasInf/BackEnd_V2 pull request #1
Opened 2023-07-31 15:32 UTC by MartynasInf

For code review

2023-07-31 15:36 UTC, epr0 commented on src/main/java/com/example/Street_manager/controller/UserController.java
> +
Why this place has an empty line?

2023-07-31 15:36 UTC, epr0 commented on src/main/java/com/example/Street_manager/controller/UserController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
Use logging to capture error messages to be more informative.

2023-08-03 15:15 UTC, epr0 requested changes
Left an initial portion to warm up.

2023-08-03 15:15 UTC, epr0 commented on .mvn/wrapper/maven-wrapper.properties
> +# Licensed to the Apache Software Foundation (ASF) under one
Don't commit files which are not needed.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/Interface/DataChecker.java
> +public interface DataChecker<T> {
You can document the purpose of the interface with a javadoc.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/config/JwtAuthenticationFilter.java
> +        //patikrinam ar pries tai nebuvo autentifikuotas
If you are leaving/using comments use them in english to maintain consisntency

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/controller/Authentication/AuthenticationController.java
> +//    @GetMapping("/home")
Eventually get rid of commented out code.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/controller/HouseController.java
> +    public ResponseEntity<?> findAll() {
Remind me why the wild card "?" is needed here?

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/controller/HouseController.java
> +        } catch (Exception e) {
Would be good practice to add a logger with some more detailed information for developer if exception happens.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/PaymentOperationService.java
> +                PaymentOperationDto paymentOperationDto = PaymentOperationDto.builder()
This chunk for building the object can be extracted to separate method.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/HousePaymentService.java
> +    public void payThePayment(HousePaymentDto housePaymentDto) {
Maybe simple "pay" would be better? PaymentService has a capability to "pay".

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/HousePaymentService.java
> +            HousePayment housePayment = housePaymentRepository.findById(housePaymentDto.getId()).orElseThrow(() -> ResponseException.builder()
formatting?

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/HousePaymentService.java
> +        return (BigDecimal.valueOf(paymentRequest.getTotalSum() / paymentRequest.getHouseIds().size())
pretty difficult to read. Remember - not every time less lines are better.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/HouseService.java
> +        for (House house : houses) {
Extract object creation to a separate method, replace for with streams/foreach

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/HouseService.java
> +        if (!checkIfHouseHasOwner(houseId)) {
Avoid "!" , change the naming and purpose of method. "hasHouseOwner" "isOwnerPresent" , etc

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/HouseService.java
> +    public void validateGivenHouseDetailsFields(HouseDto houseDto, List<String> fieldNames) {
What is the purpose of this method?

2023-08-03 15:15 UTC, epr0 commented on mvnw
> +#!/bin/sh
no need to commit these types of files. Make repo as clean as possible.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/controller/Authentication/AuthenticationController.java
> +    public ResponseEntity<AuthenticationResponseDto> authenticate (@RequestBody AuthenticationRequestDto request){
Formatting?

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/controller/PaymentOperationController.java
> +            return ResponseEntity.status(HttpStatus.OK).body(paymentOperationService.getAll());
dont make this as compact as possible. difficult to debug. Get all the paymentOperations stored in variable, the return it.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/controller/PaymentOperationController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
logging.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/dto/Authentication/AuthenticationResponseDto.java
> +
empty spaces

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/enums/PaymentOperationStatus.java
> +    CREATION,
Maintain naming consistency. Creation, Activation, Archivation or Create, Active, Archive, or Created, Activated, Archived.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/exception/ResponseException.java
> +public class ResponseException extends RuntimeException{
formatting?

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/model/House.java
> +import javax.persistence.*;
Avoid * improrts.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/Authentication/JwtService.java
> +    //!!!geriau butu laikyti application properties
So hold it in the application properties :)

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/HouseService.java
> +    private UserDetailsDto mapToUserDetails(House house) {
Why are you passing the house here, if you are using only user object within the house? Pass User object instead and avoid using house.getuser() in every row.

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/PaymentOperationService.java
> +        } catch (Exception e) {
Is it really necessary? What kind of exception are you expecting here?

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/PaymentOperationService.java
> +                    .id(housePayment.getHouse().getUser().getId())
housePayment.getHouse().getUser() in every line. Code duplication. Maybe pass the user to this method instead?

2023-08-03 15:15 UTC, epr0 commented on src/main/java/com/example/Street_manager/service/UserService.java
> +    public void validateGivenUserDetailsFields(UserDetailsDto user, List<String> fieldNames) {
looks a bit complicated method? Have you had any ideas how to implemented?

2023-08-06 08:08 UTC, MartynasInf commented on src/main/java/com/example/Street_manager/controller/HouseController.java
> +    public ResponseEntity<?> findAll() {
I'm using this wild card because if everything goes right - it returns an object or a list of objects. If something goes wrong, it returns error message. "?" is needed to have this flexibility of return types, that means i can return anything. Error message is used in browser console to check the error message. This message will be used in front end view that user could see what happened wrong.

2023-08-06 08:15 UTC, MartynasInf commented on src/main/java/com/example/Street_manager/controller/PaymentOperationController.java
> +            return ResponseEntity.status(HttpStatus.OK).body(paymentOperationService.getAll());
You mean 1. Retrieve all the payment operations from db. 2. Put it to map service and put it in a variable (list of mapped payment operations). 3. Return it  ? Everything done in the controller endpoint ? Or you mean in paymentOperationService.getAll() method return  should be variable, not a call to another method ?

2023-08-06 09:04 UTC, MartynasInf commented on src/main/java/com/example/Street_manager/service/Authentication/JwtService.java
> +    //!!!geriau butu laikyti application properties
Done it in simple way without creating JwtConfig file with incapsulation. As this is small program, it is not needed for complex solutions (i guess)

2023-08-06 09:06 UTC, MartynasInf commented on src/main/java/com/example/Street_manager/service/HousePaymentService.java
> +    public void payThePayment(HousePaymentDto housePaymentDto) {
Agree. There are no other payments (yet) and if there will be - my naming does not describe what is being paid as there can be a lot of different payment operations.

2023-08-06 13:17 UTC, MartynasInf commented on src/main/java/com/example/Street_manager/service/HouseService.java
> +    public void validateGivenHouseDetailsFields(HouseDto houseDto, List<String> fieldNames) {
This method validates given House object fields is not null. It is used for object creation + object update. It checks that fields that i think is a "must", have values. Sure, now to think of i could make some of the fields that are checked repeatedly by this method just @NotNull (cant remember if this is the right annotation) and just check those few fields who vary through the processes. At this case i just need few separate methods for these fields checking. But this exact method can be more versatile for future checks if there will be additional fields on classes. I will just update my string list with 1 additional string instead of writing another method for check.

2023-08-15 12:52 UTC, MartynasInf commented on src/main/java/com/example/Street_manager/service/UserService.java
> +    public void validateGivenUserDetailsFields(UserDetailsDto user, List<String> fieldNames) {
Yes, it's complicated. But as i put all the info through API with received Dto form my front, i dont want to put @NotNull annotation, because i dont know, maybe on the future development i wont need that field for some reason in Dto received information. And other practices is unknown, how i should manage received info from Dto and make sure my needed fields is not null. Sure i could create another Dto, but i dont think it is good idea as for every future operation where i will need other specific fields filled, i will need to create another dto class. With this method i dont need to do that.

2023-08-15 14:32 UTC, MartynasInf commented on src/main/java/com/example/Street_manager/service/PaymentOperationService.java
> +        } catch (Exception e) {
Made my entity classes as @NotNull so no other macroservice could put null value to database. In that case i can delete this exception handling as the values are taken from database and mapped to dto class. There should be no null values. Made extra adjustment and added @NotBlank annotations to prevent empty string values from database

2023-11-06 18:35 UTC, merged